### ISSUE TITLE
Estudar sobre o sistema do login

### ISSUE THREAD

**Issue by Nandosts** [Nandosts/Ressaca-trainee#13]
Necessário.

**Comment by BomDia12** [comment]
Bem, eu estudei sobre o Sorcery, e assim, é uma dor de cabeça do caramba kkkk, mas basicamente, cada coisa tem um método novo, tipo, dá pra colocar um before_action :require_login, pra restringir as funções, e tá funcionando, kkkk.

**Comment by LordeFelipe** [comment]
Tutorial útil: https://github.com/Sorcery/sorcery/wiki/Simple-Password-Authentication
